name: satz-compose-dev

services:
  # Development service for frontend (optional, can still use npm run dev locally)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - VITE_API_URL=http://backend:3000
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - satz-network

  # Development service for backend (optional, can still use deno run locally)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/app
    command: deno run --watch --allow-read --allow-env --allow-net main.ts
    env_file:
      - .env.local
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - satz-network

  db:
    image: postgres:17.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - satz-network

networks:
  satz-network:
    driver: bridge

volumes:
  postgres_data:
